apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-rfz1
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0033-tenant/tkrw-pr712-0075-0033-app/devfile-sample-rfz1@sha256:c3351b3f04b0eb8486159ed1c90368a9ba4e7c19b2e8f97fe50556a8b9329a4a
        name: my-nodejs
        resources: {}
status: {}
